version: '2'

services:
  myapp:
    image: 'docker.io/bitnami/symfony:1-debian-10'
    ports:
      - '8000:8000'
    volumes:
      - '.:/app/myapp'
      - './php.ini:/opt/bitnami/php/conf/php.ini'
    depends_on:
      - mariadb
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: example
#      - ALLOW_EMPTY_PASSWORD=no
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
